services:

  server_time_management_db:
    image: mysql:8.0
    container_name: server_time_management_db
    ports:
      - 3900:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: time_management_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  server_time_management_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server_time_management_app
    restart: always
    ports:
      - 8900:80
    volumes:
     - ./src:/var/www/html
     - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: /var/www/html
    cap_add:
        - SYS_ADMIN
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=server_time_management_db
      - DB_PORT=3306
      - DB_DATABASE=time_management_db
      - DB_USERNAME=user
      - DB_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
